project:
  type: book
  output-dir: docs
  # output-dir: pdfs
  preview:
    port: 7771
    browser: false
  resources:
    - "data/*.mp3"
  render:
    - "*.qmd"
    - "!*.Rmd"
    - "!to_do.qmd"

lang: ko-KR

# ---------------------------------- #
book:
  title: "챗GPT 데이터 과학"
  reader-mode: true
  subtitle: "AI와 함께하는 데이터 과학 여정"

  page-footer:
    left: |
      챗GPT 데이터 과학 책은 소프트웨어 카펜트리 "R for Reproducible Scientific Analysis"를 번역한 것이 포함되어 있습니다.
    right: |
      순수하게 <a href="https://quarto.org/">쿼토(Quarto)</a>로 제작되었습니다.

  cover-image: images/logo.png
  favicon: images/logo.png
  site-url: https://r2bit.com/gpt-ds/
  repo-url: https://github.com/bit2r/gpt-ds
  repo-branch: main
  repo-actions: [edit, issue]

  google-analytics: "UA-229551680-1"
  author:
    - name: "이광춘"
      affiliations: "공익법인 한국 R 사용자회"
  date: last-modified
  date-format: "YYYY년 MM월 DD일"

  chapters:
    - index.qmd

    - part: "**1부** 들어가며"
      chapters:
        - intro.qmd
        - whole_game.qmd
        - penguins.qmd

    - part: "**2부** 데이터 다루기"
      chapters:
        - data_structure.qmd
        - dataframe.qmd

    - part: "**3부** 가져오기"
      chapters:
        - import.qmd

    - part: "**3부** 데이터 과학"
      chapters:
        - simpson.qmd
        - basic_stat.qmd
        - sampling.qmd
        - hypothesis.qmd
        - NHST.qmd

    - part: "**4부** 모형"
      chapters:
        - models.qmd
        - models_building.qmd
        - models_many.qmd
        - models_case_study.qmd

    - part: "**5부** 프로그래밍"
      chapters:
        - functions.qmd
        - functions_ds.qmd
        - functions_purrr.qmd

    - part: "**6부** 커뮤니케이션"
      chapters:
        - quarto.qmd
        - map.qmd

    - part: "**7부** 챗GPT"
      chapters:
        - prompt.qmd
        - langchain.qmd
        - code_interpreter.qmd
        - llm_python.qmd
        - local_llm.qmd
        - lang_gpt.qmd

    - references.qmd

    # - part: "**2부** 언어"
    #   chapters:
    #     - lang_r.qmd
    #     - lang_py.qmd
    #     - lang_sql.qmd

# ---------------------------------- #

format:
  html:
    theme:
      light: [cosmo, r2bit.scss]
    mermaid:
      theme: neutral # https://quarto.org/docs/authoring/diagrams.html#mermaid-theming
    number-depth: 3
    number-sections: true
    colorlinks: true
    # cite-method: biblatex
    code-overflow: wrap
    code-link: true

    author-meta: "이광춘, 신종화"
    callout-appearance: simple

    # 마크다운 표 캡션 위치
    tbl-cap-location: bottom

# ---------------------------------- #
filters:
  - lightbox
  - fontawesome
  - include-code-files
  - fancy-text
  - webr
  # - pyodide
lightbox: auto

webr:
  packages:
  - "stringr"
  # - "readr"
  # - "purrr"
  # - "httr"
  # - "curl"
  # - "rvest"
  # - "fs"
  # - "ggplot2"
  - "palmerpenguins"

code-annotations: hover

bibliography: references.bib
link-citations: false

# ---------------------------------- #
engine: knitr

knitr:
  opts_chunk:
    message: false
    warning: false
    collapse: true
    code-overflow: code-overflow
    fig-crop: false
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true
editor_options:
  chunk_output_type: console

editor:
  source: true
  markdown:
    wrap: 72


