project:
  type: book
  output-dir: docs

lang: ko-KR

book:
  title: "챗GPT 데이터 과학"
  reader-mode: true

  page-footer:
    left: |
      이광춘, 신종화, 유충현, 홍성학이 '챗GPT 데이터 사이언스'를 저작했습니다.
    right: |
      <a href="https://quarto.org/">쿼토(Quarto)</a>로 제작.
  cover-image: cover.jpg
  favicon: cover.jpg
  site-url: https://r2bit.com/chatGPT4ds/
  repo-url: https://github.com/bit2r/chatGPT4ds
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd

    - part: "tidyverse"
      chapters:
        - intro.qmd

    - part: "데이터셋"
      chapters:
        - penguins.qmd

    - part: "언어"
      chapters:
        - lang_gpt.qmd
        - lang_r.qmd
        - lang_py.qmd
        - lang_sql.qmd

    - part: "데이터 과학"
      chapters:
        - simpson.qmd
        - basic_stat.qmd
        - intermediate_stat.qmd
    - part: "프로그래밍"

    - part: "커뮤니케이션"
      chapters:
        - quarto.qmd

    - part: "챗GPT"

    - part: "-----"


format:
  html:
    theme:
      - cosmo
      - chatGPT4ds.scss
    code-link: true

    author-meta: "이광춘, 신종화"
    callout-appearance: simple

editor: source

filters:
   - lightbox
lightbox: auto
link-citations: true


knitr:
  opts_chunk:
    message: false
    warning: false
    collapse: false
editor_options:
  chunk_output_type: console
