project:
  type: book
  output-dir: docs
  render:
    - "!map_pdf.qmd"

lang: ko-KR

book:
  title: "챗GPT 데이터 과학"
  subtitle: "AI와 함께하는 데이터 과학 여정"

  reader-mode: true

  page-footer:
    left: |
      이광춘, 신종화, 유충현, 홍성학이 '챗GPT 데이터 사이언스'를 저작했습니다.
    right: |
      <a href="https://quarto.org/">쿼토(Quarto)</a>로 제작.
  cover-image: images/logo.png
  favicon: images/logo.png
  site-url: https://r2bit.com/chatGPT4ds/
  repo-url: https://github.com/bit2r/chatGPT4ds
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd

    - part: "**1부** 들어가며"
      chapters:
        - intro.qmd
        - whole_game.qmd
        - penguins.qmd

    - part: "**2부** 가져오기"
      chapters:
        - import.qmd

    - part: "**2부** 언어"
      chapters:
        - lang_gpt.qmd
        - lang_r.qmd
        - lang_py.qmd
        - lang_sql.qmd

    - part: "**3부** 데이터 과학"
      chapters:
        - simpson.qmd
        - basic_stat.qmd
        - sampling.qmd
        - hypothesis.qmd
        - NHST.qmd

    - part: "**4부** 모형"
      chapters:
        - models.qmd
        - models_building.qmd
        - models_many.qmd
        - models_case_study.qmd

    - part: "**5부** 프로그래밍"
      chapters:
        - functions.qmd
        - functions_ds.qmd
        - functions_purrr.qmd

    - part: "**6부** 커뮤니케이션"
      chapters:
        - quarto.qmd
        - map.qmd

    - part: "**7부** 챗GPT"
      chapters:
        - prompt.qmd
        - langchain.qmd
        - code_interpreter.qmd
        - llm_python.qmd
        - local_llm.qmd

    - references.qmd

format:
  html:
    theme:
      - cosmo
      - chatGPT4ds.scss
    number-depth: 3
    number-sections: true
    colorlinks: true
    # cite-method: biblatex
    code-overflow: wrap
    code-link: true

    author-meta: "이광춘, 신종화"
    callout-appearance: simple

editor: source

filters:
   - lightbox
lightbox: auto
link-citations: true

bibliography: references.bib

knitr:
  opts_chunk:
    message: false
    warning: false
    collapse: false
editor_options:
  chunk_output_type: console


execute:
  freeze: auto

